### ISSUE TITLE
New files to push

### ISSUE THREAD

**Issue by hkashiwase** [worldbank/pddcs#19]
Dear Aleksander,

I have changed the two files (1. fetch-unicef.R 2.internal-variables.R) to add 4 new UNICEF indicators and committed in R.  However, it doesn't seem that I can push the files in Git.  I have created a new branch called "add_unicef_indicators".  Could you help me with how to push the files?  Thanks for your help.

Haruna

![image](https://user-images.githubusercontent.com/43618165/121942724-ce5f5800-cd1e-11eb-853e-d81d7d2d68c9.png)
![image](https://user-images.githubusercontent.com/43618165/121943138-44fc5580-cd1f-11eb-8cd1-ec4a1fb89a46.png)

**Comment by Aeilert** [comment]
Dear Haruna, 

Thanks for updating the files. I saw you already pushed some files to the `add_unicef_indicators` [branch on Github](https://github.com/worldbank/pddcs/tree/add_unicef_indicators). But I can see how the messages in RStudio can be a bit confusing. 

From the "log on failed" message it looks like RStudio is not able to access your Github account. Maybe take a look at  [Connect RStudio to Git and GitHub](https://happygitwithr.com/rstudio-git-github.html) to see if these steps could help. The "everything up-to-date" message does however indicate that all your local commits are already pushed, so check the Github branch https://github.com/worldbank/pddcs/tree/add_unicef_indicators to see if your changes are already there. 

Once you have pushed the final changes you can create a [Pull Request](https://github.com/worldbank/pddcs/compare/master...add_unicef_indicators)  and assign me as a reviewer. 

Best,
Aleksander

**Comment by hkashiwase** [comment]
Dear Aleksander, thank you for your instruction!  I have just submitted a pull request.  Please let me know if you find any problems.  

Haruna
