### ISSUE TITLE
Metadata for WHO data

### ISSUE THREAD

**Issue by hkashiwase** [worldbank/pddcs#21]
Dear Aleksander,

For the **WHO metadata**, could you retrieve the confidence interval instead of the data source?  

For example, [WHO's suicide API ]( https://ghoapi.azureedge.net/api/SDGSUICIDE)provides the following data(both sex) and CI for AFG in 2019: ""Value":"4.1 [2.3-7.0]".  For the metadata, I would like to ask you to retrieve the CI [2.3-7.0] and write as follows: "Plausible bound is 2.3-7.0."
![image](https://user-images.githubusercontent.com/43618165/125505017-f87471a4-68f7-4d8c-8535-bfeec1f68015.png)

I would like to ask you to create the metadata by showing CI as above for all the WHO indicators.  Please do not make changes to the UNICEF metadata.  

Thank you very much for your consideration.  Feel free to let me know if you have any questions.

Best,
Haruna

**Comment by Aeilert** [comment]
Dear Haruna, 

Thank you for your request. This has now been added. See the latest package version (0.0.0.**9302**). 


```
> df <- fetch_indicator('SH.STA.SUIC.P5', 'who')
> df <- format_dcs(df, type = 'meta')
> head(df)

# A tibble: 6 x 4
  Country Series         Time   Footnote                   
  <chr>   <chr>          <chr>  <chr>                      
1 AFG     SH.STA.SUIC.P5 YR2000 Plausible bound is 2.8-8.0.
2 AFG     SH.STA.SUIC.P5 YR2001 Plausible bound is 2.9-8.2.
3 AFG     SH.STA.SUIC.P5 YR2002 Plausible bound is 2.9-8.2.
4 AFG     SH.STA.SUIC.P5 YR2003 Plausible bound is 2.8-8.1.
5 AFG     SH.STA.SUIC.P5 YR2004 Plausible bound is 2.9-8.2.
6 AFG     SH.STA.SUIC.P5 YR2005 Plausible bound is 2.9-8.1.
```

Best, 
Aleksander
